### ISSUE TITLE
SARIF standardization

### ISSUE THREAD

**Issue by Gby56** [reviewdog/reviewdog#1175]
Hello hello ! 👋 
I'm a maintainer on https://github.com/security-alert/security-alert with @azu and I just discovered your project !
I searched for SARIF and saw the early issues/PRs, and it seems that there was a path for SARIF in experimental...

Is there any chance that SARIF would be supported ? I can start looking into it a bit, I would love to provide support for that even if security-alert already does that, but I think reviewdog has better commenting (exact line?) and interface

**Comment by Gby56** [comment]
Seems like https://github.com/g-wilson/action-semgrep already exists

**Comment by haya14busa** [comment]
Yes, SARIF support as input/output of reviewdog should be great improvement.
Alternative option would be create a tool to convert RDFormat <=> SARIF (https://github.com/reviewdog/reviewdog/issues/628). 
I just do not have chances/time to support it. Any contributions are welcome :)

I do not understand why action-semgrep is related to this issue.
Looks like it just manually format results instead of consuming nor converting SARIF data.
https://github.com/g-wilson/action-semgrep/blob/17b8bb7e7e42395cac39548fe732df3a816351bc/entrypoint.sh#L10-L13

**Comment by jcook-uptycs** [comment]
@Gby56 which PR did you find with SARIF support? I can't find it. Also were you able to work on it?

**Comment by irgaly** [comment]
Reviewdog v0.15.0 supports SARIF now.

https://github.com/reviewdog/reviewdog/releases/tag/v0.15.0
