### ISSUE TITLE
'github-pr-review' reporter is not making suggestion for blank line addition

### ISSUE THREAD

**Issue by OnkarRuikar** [reviewdog/reviewdog#1580]
- related to https://github.com/mdn/content/pull/29332#issuecomment-1740072618

I've reproduced it in a test environment. In [this test PR](https://github.com/OnkarRuikar/content/pull/26) for [the commit](https://github.com/OnkarRuikar/content/pull/26/commits/fd57312e70913e5219883ad3455a6caec5c600ee) in workflow `lint-and-review-docs` Prettier [is suggesting one blank line addition](https://github.com/mdn/content/actions/runs/6344733340/job/17235461560#step:8:56) but reviewdog is not able to make a review comment about it.

**Comment by massongit** [comment]
I created https://github.com/massongit/content/pull/1 with the same content as https://github.com/OnkarRuikar/content/pull/26.
In this PR, there is no difference in https://github.com/massongit/content/blob/fd57312e70913e5219883ad3455a6caec5c600ee/files/en-us/games/index.md?plain=1#L18.
Prettier expects a difference below to apply this line.

```md

## Port native games to the Web
```

However, it seems that reviewdog does not add a review comment unless it is an additional line.

**Comment by haya14busa** [comment]
I found that it should be due to `-filter-mode=added` (default). 
The inserted blank line is not within added lines. That's why reviewdog doesn't report the problem.

To fix the problem, you can use `-filter-mode=diff_context`. 

Or if you use https://github.com/reviewdog/action-suggester, then it set `-filter-mode=diff_context` internally by default.
