### ISSUE TITLE
[github-pr-review] zero location for lines does not work

### ISSUE THREAD

**Issue by sobolevn** [reviewdog/reviewdog#360]
Hello! Thanks a lot for this wonderful project!

I am implementing a `reviewdog`-based Github Action for https://github.com/wemake-services/wemake-python-styleguide
Original PR: https://github.com/wemake-services/wemake-python-styleguide/pull/1024

The problem is that we have some errors that are logically located on `0` line.
Like these ones:

```
./wrong__01.py:0:1: WPS114 Found underscored name pattern: wrong__01
./wrong__01.py:1:1: WPS111 Found too short name: a
```

As you see, we cannot report `Found underscored name pattern: wrong__01` on first line. Because it does not make any sense. And `reviewdog` does not show this error inside the pull request: https://github.com/wemake-services/wemake-python-styleguide/pull/1024#pullrequestreview-322932150

What should I do here?

**Comment by sobolevn** [comment]
My PRs:
- https://github.com/wemake-services/wemake-python-styleguide/pull/1045
- https://github.com/sobolevn/python-pure-evil/pull/1

**Comment by haya14busa** [comment]
For github-pr-review, we cannot support reporting errors to arbitrary locations due to GitHub API limitation. We can only post comments to lines inside PR diff.

Alternatively, it can be possible to post comments as a review summary comment, but it's not implemented yet.

As for github-pr-check, Check API supports posting comments outside diff, so it's possible to post a comment to file as line 1, but it's not implemented either.

**Comment by haya14busa** [comment]
Now you can use `-filter-mode=file` or `-filter-mode=nofilter` to include zero line results. https://github.com/reviewdog/reviewdog#filter-mode
