### ISSUE TITLE
New Linter: yamllint

### ISSUE THREAD

**Issue by aslafy-z** [reviewdog/reviewdog#402]
Hello! 

I added support for yamllint. You can find it in here: https://github.com/aslafy-z/reviewdog-yamllint-action.

**Comment by haya14busa** [comment]
Cool! Do you want to move the repo under reviewdog org and/or release the action?

**Comment by aslafy-z** [comment]
I'm okay to move it under `reviewdog` org!

**Comment by haya14busa** [comment]
I invited you to reviewdog org, so please feel free to move the repo. (I'm actually either is fine. You can maintain it under your account too.)

Probably you should not use "fork" because github cannot fork the same original repo more than once.

e.g. If a user forked reviewdog/action-eslint before, the user cannot fork aslafy-z/reviewdog-yamllint-action as different repo because they already forked the original one.

**Comment by haya14busa** [comment]
Also, can you clean it up a bit more? e.g. Screenshot still uses eslint.
