### ISSUE TITLE
[github-pr-review] Mark outdated review comments as obsolete or delete such comments

### ISSUE THREAD

**Issue by haya14busa** [reviewdog/reviewdog#568]
With github-pr-review, if a reported line is changed to fix the reported problem, GitHub marks the comment as outdated. However, if the fix doesn't change the reported line, the previously reported comment still remains as is.

github-pr-review reporter fetches reported comments first to prevent posting the same comments, so it should be possible to detect which comments are fixed by comparing the new reported results.

It should be better to resolve fixed reported results (or mark them as obsolete or delete such comments?).

IMPACT: This problem can happen  for type check based on comment. e.g. phpstan, jsdoc type check of Typescript.

Just for reference  (in Japanese though): https://twitter.com/about_hiroppy/status/1258699418796097537

**Comment by haya14busa** [comment]
Note that we may want to implement similar feature to `gitlab-mr-duscission` reporter as well.
Also, it should be no problem with github-check (and github-pr-check) reporters because it always reports all results to a specific commit hash, not as PR comments.

**Comment by haya14busa** [comment]
I don't plan to work on it immediately, so please feel free to take this issue if you're interested in it. cc/ @reviewdog/reviewdog

**Comment by dbackeus** [comment]
It's quite nice to delete linting comments to avoid leaving long trails of old PR activity. We've been using houndci.com for linting and when they switched from resolving to deleting comments our PR's got a whole lot cleaner. Maybe this behaviour needs to be configurable since I don't know if deleting makes sense for all kinds of reviewdog checkers?

**Comment by jeff-cook** [comment]
GitLab has the idea of resolve thread or discussion. That would be great to see. Not to delete the discussion, but to make it resolved. 

Having this cleaned up for fixed issues would be awesome!

**Comment by tmshn** [comment]
As far as I checked quickly, the REST API has no method to resolve review comments; only the GraphQL API has.

- REST: https://docs.github.com/en/rest/reference/pulls
- GraphQL: https://docs.github.com/en/graphql/reference/mutations#resolvereviewthread

reviewdog currently using REST API, so we can't mark review comments as "resolved".

The only choice currently available seems to be deletion.

**Comment by dbackeus** [comment]
To elaborate on the deletion behaviour of HoundCI: It only deletes comments if there was no follow up. So "discussions" would be left in place. In my experience it's quite uncommon for discussions to occur on linting comments though.

**Comment by mattboldt** [comment]
Any updates on this? I'm moving from CodeClimate to reviewdog + GH actions and I'm trying to decide between `github-pr-review` or `github-pr-check`.

`github-pr-check` is nice in that it marks the build as a failure, and once you resolve linting issues locally and push again, the stale annotations are removed and the build is now a success. The downside here is there's no way to manually dismiss an annotation (akin to CodeClimate's options for "invalid" or "wontfix" for certain warnings).

`github-pr-review` allows you to manually resolve a warning, but because stale comments aren't deleted or resolved, it kinda floods the PR with comments.

I'm thinking `github-pr-review` is the lesser of the evils here, but it'd be nice to have the best of both worlds.

**Comment by xuwei-k** [comment]
https://github.com/Ardiannn08/resolve-outdated-comment

**Comment by dbackeus** [comment]
Not a fix for reviewdog in general. But for people using reviewdog for running Rubocop in particular, we made an alternative GitHub action which does proper deletion of outdated comments: https://github.com/reclaim-the-stack/rubocop-action

NOTE: This is cleaner than "resolving" comments since it fully clears the PR history of linting noise.
