### ISSUE TITLE
Run remaining linters when first linter fails together with `-fail-on-error`

### ISSUE THREAD

**Issue by ruudk** [reviewdog/reviewdog#638]
https://github.com/reviewdog/reviewdog/pull/504 adds the `-fail-on-error` option but I think that should have been called `-fail-on-first-error`. If you have multiple linters, and the first linter fails, it will stop immediately, without running the other linters.

My suggestion would be:

* Rename `-fail-on-error` to `-fail-on-first-error`. As soon as 1 linter fails, exit immediately with an error code.
* Implement new `-fail-on-error` that will run all linters, and if one or more linters fails, it will exit with an error code.

This makes the feedback loop faster when running in a CI. It will show all your errors on the commit that you did, instead of having to fix, push, wait, fix, push, wait, repeat.

**Comment by ruudk** [comment]
@DmitryLanda @mgrachev @haya14busa Ping because you were involved in the original PR. What do you think?

**Comment by haya14busa** [comment]
Thanks for the report, but this is actually by design and I don't think failing on first error makes the feedback-loop faster. In fact, I believe it will slow down the feedback loop.

If it fails with first error and won't return the rest results, the same thing you described happens more frequently because users don't know the rest report.
Fix, push, wait, fix, push, wait, repeat.
Users couldn't fix the all errors with one feedback loop because they don't know the all errors, right?
reviewdog should report all results.

You should run linters locally to make the loop faster if a certain linter reports too many errors and cannot fix all of them at once.

**Comment by ruudk** [comment]
You are right :)
