### ISSUE TITLE
Check original line number and commit not to post same comments

### ISSUE THREAD

**Issue by haya14busa** [reviewdog/reviewdog#87]

**Comment by JensRantil** [comment]
I'm am, too, interested in this. Would you mind if I submit a pull request for this?

**Comment by haya14busa** [comment]
Sure. Do you have some rough design or something?

**Comment by JensRantil** [comment]
@haya14busa Did migrating to a checker fix this issue?

**Comment by haya14busa** [comment]
yes. For check API, we don't need to care about this problem.

reviewdog is still supporting reports through github review comments, so the problem isn't solved yet for -reporter=github-pr-review.

but i'll close this issue for now because i don't have plan to work on this issue. maybe we can re-visit later.
Thanks :)

**Comment by JensRantil** [comment]
:+1: Just curious, any particular reason to keep the old reviewer? Since the checks API seems better in every single way, maybe the old could be removed?

**Comment by haya14busa** [comment]
New checks API is generally better, but the API is only available for GitHub apps.
So, reviewdog CLI need to talk to reviewdog server I created and the server will post Check API to GitHub.

As for  -reporter=github-pr-review feature, reviewdog CLI directly talks to GitHub with personal access token.

For private repo users who don't want to, or it's difficult to trust my reviewdog server, it's better to use github-pr-review feature because it works standalone. 

As for OSS repository, I think users should choose github-pr-check reporter by default unless the reviewdog server is broken ;)

**Comment by JensRantil** [comment]
> For private repo users who don't want to, or it's difficult to trust my reviewdog server, it's better to use github-pr-review feature because it works standalone.

@haya14busa Ok. In that case, this issue is still standing for private repos. Would you mind reopening it (and maybe modify description that it's only relevant for private repos)? Or would you like me to create a new issue?

> Do you have some rough design or something?

1) find the first comment by its own user and 2a) if found, modify the comment; otherwise 2b) post a new comment. This is what [CodeCov](https://codecov.io/) does. See [here](https://github.com/codecov/example-python/pull/26#issuecomment-356086692) for an example (click "Edited" in the comment header). What do you think of this approach?

**Comment by JensRantil** [comment]
> Would you mind reopening it (and maybe modify description that it's only relevant for private repos)?

@haya14busa Ping.

**Comment by haya14busa** [comment]
This may fixed one reviedog supports GitHub actions

**Comment by haya14busa** [comment]
The latest reviewdog supports GitHub Action and can use github-pr-check reporter.
